export interface FxState {
	preset: number;
	intensity: number;
	cinemaShake: number;
	depth: number;
	coverResolution: number;
	point: number;
	speed: number;
	twist: number;
	color: number;
	scatter: number;
	bgFade: number;
	bloomStrength: number;
	lyricGlowStrength: number;
	lyricScale: number;
	lyricOffsetX: number;
	lyricOffsetY: number;
	lyricOffsetZ: number;
	lyricTiltX: number;
	lyricTiltY: number;
	lyricColorMode: string;
	lyricColor: string;
	lyricHighlightMode: string;
	lyricHighlightColor: string;
	lyricGlowLinked: boolean;
	lyricGlowColor: string;
	lyricFont: string;
	lyricLetterSpacing: number;
	lyricLineHeight: number;
	lyricWeight: number;
	visualTintMode: string;
	visualTintColor: string;
	uiAccentColor: string;
	homeAccentColor: string;
	homeIconColor: string;
	visualIconColor: string;
	backgroundColorMode: string;
	backgroundColor: string;
	backgroundOpacity: number;
	controlGlassChromaticOffset: number;
	backgroundColorCustom: boolean;
	backgroundImage: string;
	backgroundMedia: unknown | null;
	desktopLyrics: boolean;
	desktopLyricsSize: number;
	desktopLyricsOpacity: number;
	desktopLyricsY: number;
	desktopLyricsClickThrough: boolean;
	desktopLyricsCinema: boolean;
	desktopLyricsHighlight: boolean;
	desktopLyricsFps: number;
	wallpaperMode: boolean;
	wallpaperOpacity: number;
	floatLayer: boolean;
	cinema: boolean;
	edge: boolean;
	aiDepth: boolean;
	bloom: boolean;
	lyricGlow: boolean;
	lyricGlowBeat: boolean;
	lyricGlowParticles: boolean;
	lyricCameraLock: boolean;
	particleLyrics: boolean;
	backCover: boolean;
	shelf: string;
	shelfCameraMode: string;
	shelfPresence: string;
	shelfShowPodcasts: boolean;
	shelfMergeCollections: boolean;
	shelfSize: number;
	shelfOffsetX: number;
	shelfOffsetY: number;
	shelfOffsetZ: number;
	shelfAngleY: number;
	shelfAngleYManual: boolean;
	shelfOpacity: number;
	shelfBgOpacity: number;
	shelfAccentColor: string;
	performanceBackground: string;
	performanceQuality: string;
	liveBackgroundKeep: boolean;
	cam: string;
	mouseActive: boolean;
	mouseXy: { x: number; y: number };
	burstAmt: number;
	vinylSpin: number;
	particleDim: number;
}

export const FX_DEFAULTS: FxState = {
	preset: 0,
	intensity: 0.85,
	cinemaShake: 0.5,
	depth: 1.0,
	coverResolution: 1.55,
	point: 1.0,
	speed: 1.0,
	twist: 0.0,
	color: 1.10,
	scatter: 0.0,
	bgFade: 0.20,
	bloomStrength: 0.62,
	lyricGlowStrength: 0.28,
	lyricScale: 1.0,
	lyricOffsetX: 0,
	lyricOffsetY: 0,
	lyricOffsetZ: 0,
	lyricTiltX: 0,
	lyricTiltY: 0,
	lyricColorMode: "auto",
	lyricColor: "#a9b8c8",
	lyricHighlightMode: "auto",
	lyricHighlightColor: "#fac900",
	lyricGlowLinked: true,
	lyricGlowColor: "#008aff",
	lyricFont: "hei",
	lyricLetterSpacing: 0,
	lyricLineHeight: 1.0,
	lyricWeight: 900,
	visualTintMode: "auto",
	visualTintColor: "#9db8cf",
	uiAccentColor: "#ffffff",
	homeAccentColor: "#ffffff",
	homeIconColor: "#ffffff",
	visualIconColor: "#ffffff",
	backgroundColorMode: "cover",
	backgroundColor: "#000000",
	backgroundOpacity: 1,
	controlGlassChromaticOffset: 90,
	backgroundColorCustom: false,
	backgroundImage: "",
	backgroundMedia: null,
	desktopLyrics: false,
	desktopLyricsSize: 1.0,
	desktopLyricsOpacity: 0.92,
	desktopLyricsY: 0.76,
	desktopLyricsClickThrough: false,
	desktopLyricsCinema: true,
	desktopLyricsHighlight: false,
	desktopLyricsFps: 60,
	wallpaperMode: false,
	wallpaperOpacity: 1,
	floatLayer: false,
	cinema: true,
	edge: false,
	aiDepth: false,
	bloom: false,
	lyricGlow: true,
	lyricGlowBeat: true,
	lyricGlowParticles: false,
	lyricCameraLock: false,
	particleLyrics: true,
	backCover: false,
	shelf: "side",
	shelfCameraMode: "static",
	shelfPresence: "always",
	shelfShowPodcasts: false,
	shelfMergeCollections: false,
	shelfSize: 1,
	shelfOffsetX: 0,
	shelfOffsetY: 0,
	shelfOffsetZ: 0,
	shelfAngleY: -15,
	shelfAngleYManual: false,
	shelfOpacity: 1,
	shelfBgOpacity: 0.90,
	shelfAccentColor: "#ffffff",
	performanceBackground: "auto",
	performanceQuality: "high",
	liveBackgroundKeep: false,
	cam: "off",
	mouseActive: false,
	mouseXy: { x: -999, y: -999 },
	burstAmt: 0,
	vinylSpin: 0,
	particleDim: 1,
};

export function cloneFxState(): FxState {
	const base: FxState = { ...FX_DEFAULTS };
	base.mouseXy = { ...FX_DEFAULTS.mouseXy };
	return base;
}